spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #当前驱动
    url: jdbc:mysql://127.0.0.1:3306/cloud-order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC #链接mysql的地址
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:/sqlmap/*.xml
feign:
  hystrix:
    enabled: true #开启hystrix
hey: 123
logging:
  level:
    com.taotao.*.*: debug
