spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #当前驱动
    url: jdbc:mysql://127.0.0.1:3306/cloud-order?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC #链接mysql的地址
    type: org.apache.commons.dbcp2.BasicDataSource
    username: root
    password: 123456
  redis:
    host: 47.104.92.87
    jedis:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 20
        max-wait: 2000ms
mybatis:
  mapper-locations: classpath:/sqlmap/*.xml
feign:
  hystrix:
    enabled: true #开启hystrix
hey: 123
