server:
  port: 9999
spring:
  application:
    name: nacos-zuul
  main:
    allow-bean-definition-overriding: true
zuul:
  sensitive-headers:
  routes:
    users:
      path: /user/**
      serviceId: nacos-user
    orders:
      path: /order/**
      serviceId: nacos-order
  add-proxy-headers: true
  add-host-header: true
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
