server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver #当前驱动
    url: jdbc:mysql://127.0.0.1:3306/cloud-test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC #链接mysql的地址
    username: root #mysql用户名
    password: 123456 #mysql密码
    type: org.apache.commons.dbcp2.BasicDataSource
  redis:
    host: 47.104.92.87
    jedis:
      pool:
        max-active: 200
        max-idle: 50
        min-idle: 20
        max-wait: 2000ms
mybatis:
  mapper-locations: classpath:/sqlmap/*.xml
feign:
  hystrix:
    enabled: true #开启hystrix
logging:
  level:
    com.taotao.user.mapper: Debug
lia:
  names: 123;
